[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    waspinator/AccelStepper
        xreef/PCF8574 library
        waspinator/AccelStepper
        olikraus/U8g2
        paulstoffregen/Encoder
        adafruit/Adafruit GFX Library
        adafruit/Adafruit SH110X